"""Scraper for 東京国際映画祭 (TIFF) — Taiwan-related news and film info.

Generated by auto_scraper (source_id=150) and promoted to production.
Fetches news articles from TIFF's Japanese news page, filtered to
Taiwan-related content.

URL pattern: {YEAR}.tiff-jp.net/news/ja/
The subdomain changes each year; we resolve the current year dynamically
by following the redirect from www.tiff-jp.net, falling back to the
calendar year.

Search is keyword-filtered server-side (?keyword=台湾) and also filtered
client-side to ensure only Taiwan-related articles are returned.
"""

import re
import time
import random
import logging
from datetime import datetime, timezone
from typing import Any, Optional
from urllib.request import urlopen
from urllib.error import URLError

import requests
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

from .base import BaseScraper, Event
from movie_title_lookup import lookup_movie_titles
from venue_registry import lookup_venue

logger = logging.getLogger(__name__)

SEARCH_KEYWORD = "%E5%8F%B0%E6%B9%BE"  # 台湾
MAX_PAGES = 5
CARD_SELECTOR = ".article"
DETAIL_LINK_SELECTOR = ".subject a"
FIELD_SELECTORS = {"title": ".subject a", "date": ".meta .date"}
DATE_REGEX = re.compile(r"(\d{4})\.(\d{2})\.(\d{2})")
SOURCE_ID_PREFIX = "tiff_jp_"
SOURCE_ID_URL_PATTERN = re.compile(r"p=(\d+)")

MAX_EVENTS = 200

_TAIWAN_KW = re.compile(
    r"台[灣湾]|taiwan|臺灣",
    re.IGNORECASE,
)


def _resolve_base_url() -> str:
    """Follow www.tiff-jp.net redirect to detect current year subdomain.
    Falls back to {current_year}.tiff-jp.net on failure."""
    try:
        resp = urlopen("https://www.tiff-jp.net", timeout=10)
        final_url = resp.url  # e.g. https://2026.tiff-jp.net/
        m = re.match(r"https://(\d{4})\.tiff-jp\.net", final_url)
        if m:
            year = m.group(1)
            logger.info("tiff_jp: resolved year from redirect → %s", year)
            return f"https://{year}.tiff-jp.net"
    except (URLError, Exception) as exc:
        logger.warning("tiff_jp: redirect resolution failed (%s), using current year", exc)
    year = datetime.now().year
    return f"https://{year}.tiff-jp.net"


def _parse_date(text: Optional[str]) -> Optional[datetime]:
    if not text:
        return None
    m = DATE_REGEX.search(text)
    if not m:
        return None
    raw = m.group(0)
    for fmt in ("%Y.%m.%d", "%Y/%m/%d", "%Y-%m-%d"):
        try:
            return datetime.strptime(raw, fmt)
        except ValueError:
            continue
    return None


def _extract_source_id(url: str) -> Optional[str]:
    m = SOURCE_ID_URL_PATTERN.search(url or "")
    return f"{SOURCE_ID_PREFIX}{m.group(1)}" if m else None


def _safe_text(card, selector: str) -> Optional[str]:
    if not selector:
        return None
    try:
        loc = card.locator(selector).first
        if loc.count() == 0:
            return None
        return (loc.inner_text(timeout=5000) or "").strip() or None
    except PWTimeout:
        return None
    except Exception as exc:
        logger.debug("selector %s failed: %s", selector, exc)
        return None


def _safe_attr(card, selector: str, attr: str) -> Optional[str]:
    if not selector:
        return None
    try:
        loc = card.locator(selector).first
        if loc.count() == 0:
            return None
        return loc.get_attribute(attr, timeout=5000)
    except PWTimeout:
        return None
    except Exception as exc:
        logger.debug("attr %s on %s failed: %s", attr, selector, exc)
        return None


def _is_taiwan_related(title: Optional[str], description: Optional[str]) -> bool:
    """Return True if the article mentions Taiwan in title or description."""
    haystack = " ".join(filter(None, [title, description]))
    return bool(_TAIWAN_KW.search(haystack))


class TiffJpScraper(BaseScraper):
    """Scrapes Taiwan-related news from Tokyo International Film Festival."""

    SOURCE_NAME = "tiff_jp"

    def scrape(self) -> list[Event]:
        base_url = _resolve_base_url()
        search_url = f"{base_url}/news/ja/"
        events: list[Event] = []
        seen_ids: set[str] = set()

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context()
            page = context.new_page()

            try:
                for page_num in range(1, MAX_PAGES + 1):
                    if len(events) >= MAX_EVENTS:
                        logger.info("tiff_jp: hit MAX_EVENTS cap; stopping")
                        break

                    url = f"{search_url}?keyword={SEARCH_KEYWORD}&paged={page_num}"
                    logger.info("tiff_jp: fetching listing page %d: %s", page_num, url)

                    # Rate-limit courtesy delay (HTTP 429 risk)
                    if page_num > 1:
                        time.sleep(random.uniform(1.5, 3.0))

                    try:
                        page.goto(url, timeout=30_000)
                        page.wait_for_load_state("networkidle", timeout=15_000)
                    except PWTimeout:
                        logger.warning("tiff_jp: timeout on page %d; skipping", page_num)
                        continue

                    cards = page.locator(CARD_SELECTOR)
                    count = cards.count()
                    if count == 0:
                        logger.info("tiff_jp: no cards on page %d; end of pagination", page_num)
                        break

                    page_events = self._extract_cards(
                        page, context, cards, count, seen_ids, base_url
                    )
                    if not page_events:
                        logger.info("tiff_jp: page %d yielded 0 Taiwan events; stopping", page_num)
                        break
                    events.extend(page_events)

            finally:
                context.close()
                browser.close()

        logger.info("tiff_jp: collected %d events", len(events))
        return events

    def _extract_cards(self, page, context, cards, count, seen_ids, base_url):
        out: list[Event] = []
        for i in range(count):
            card = cards.nth(i)
            try:
                title = _safe_text(card, FIELD_SELECTORS["title"])
                date_text = _safe_text(card, FIELD_SELECTORS["date"])

                detail_url = _safe_attr(card, DETAIL_LINK_SELECTOR, "href")
                if not detail_url:
                    detail_url = _safe_attr(card, "a", "href")
                if detail_url and detail_url.startswith("/"):
                    detail_url = f"{base_url}{detail_url}"

                source_url = detail_url or page.url
                source_id = _extract_source_id(source_url)
                if not source_id or source_id in seen_ids:
                    continue
                if not title or not date_text:
                    continue

                start_date = _parse_date(date_text)
                if not start_date:
                    continue

                # Fetch detail page body for Taiwan keyword check
                full_description: Optional[str] = None
                if detail_url:
                    try:
                        detail_page = context.new_page()
                        detail_page.goto(detail_url, timeout=30_000)
                        detail_page.wait_for_load_state("networkidle", timeout=15_000)
                        body_text = detail_page.locator("body").inner_text(timeout=5_000)
                        if body_text:
                            full_description = body_text.strip()[:2000]
                        detail_page.close()
                    except PWTimeout:
                        logger.warning("tiff_jp: detail page timeout: %s", detail_url)
                    except Exception as exc:
                        logger.debug("tiff_jp: detail page failed %s: %s", detail_url, exc)

                # Client-side Taiwan relevance filter
                if not _is_taiwan_related(title, full_description):
                    logger.debug("tiff_jp: skipping non-Taiwan article: %s", title)
                    continue

                seen_ids.add(source_id)
                out.append(
                    Event(
                        source_name=self.SOURCE_NAME,
                        source_id=source_id,
                        source_url=source_url,
                        original_language="ja",
                        name_ja=title,
                        description_ja=full_description,
                        start_date=start_date,
                        raw_title=title,
                        raw_description=full_description,
                        category=["movie"],
                    )
                )
            except Exception as exc:
                logger.warning("tiff_jp: failed to parse card %d: %s", i, exc)
                continue
        return out


# ---------------------------------------------------------------------------
# TiffScraper — Taiwan-related films from TIFF Films API
# ---------------------------------------------------------------------------

_API_URL = "https://api-{year}.tiff-jp.net/api/films"
_VENUES_API_URL = "https://api-{year}.tiff-jp.net/api/venues"
_FILM_PAGE_URL = "https://{year}.tiff-jp.net/en/lineup/film_en/{film_id}.html"
_HTML_TAG_RE = re.compile(r"<[^>]+>")
_TIFF_CINEMA_NAME_OVERRIDES = {
    "TOHOシネマズ 日比谷 スクリーン12、13 (東京宝塚ビル地下)": (
        "TOHOシネマズ 日比谷 スクリーン12・13"
    ),
}


def _flatten_venue_tree(
    venues: list[dict[str, Any]],
) -> tuple[dict[str, dict[str, Any]], dict[str, str | None]]:
    nodes: dict[str, dict[str, Any]] = {}
    parents: dict[str, str | None] = {}

    def visit(items: list[dict[str, Any]], parent_key: str | None) -> None:
        for node in items:
            if not isinstance(node, dict):
                continue
            node_id = node.get("id")
            node_key = str(node_id) if node_id is not None else None
            if node_key is not None:
                nodes[node_key] = node
                parents[node_key] = parent_key
            children = node.get("children")
            if isinstance(children, list):
                visit(children, node_key or parent_key)

    visit(venues, None)
    return nodes, parents


def _screen_to_nearest_cinema(
    venues: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    nodes, parents = _flatten_venue_tree(venues)
    result: dict[str, dict[str, Any]] = {}
    for node_key, node in nodes.items():
        if node.get("type") != "screen":
            continue
        parent_key = parents.get(node_key)
        while parent_key is not None:
            parent = nodes.get(parent_key)
            if parent is None:
                break
            if parent.get("type") == "cinema":
                result[node_key] = parent
                break
            parent_key = parents.get(parent_key)
    return result


def _resolve_film_venues(
    film: dict[str, Any],
    screen_map: dict[str, dict[str, Any]],
) -> list[dict[str, Any]] | None:
    resolved: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    film_label = film.get("film_identifier") or film.get("title_ja") or "unknown"
    for act in film.get("acts") or []:
        screen_id = act.get("venue_id")
        cinema = screen_map.get(str(screen_id))
        if cinema is None:
            logger.warning(
                "tiff: film %s has unknown TIFF screen venue_id %s; skipping film",
                film_label,
                screen_id,
            )
            return None
        api_name = cinema.get("name_ja")
        registry_name = _TIFF_CINEMA_NAME_OVERRIDES.get(api_name, api_name)
        venue = lookup_venue(registry_name)
        if (
            venue is None
            or not venue.get("is_authoritative")
            or venue.get("is_multi_venue")
            or not venue.get("id")
            or not venue.get("canonical_name_ja")
        ):
            logger.warning(
                "tiff: unresolved authoritative TIFF venue %r for film %s; "
                "skipping film",
                registry_name,
                film_label,
            )
            return None
        venue_id = str(venue["id"])
        if venue_id not in seen_ids:
            resolved.append(venue)
            seen_ids.add(venue_id)
    return resolved


def _screening_hours(acts: list[dict[str, Any]]) -> str | None:
    entries: list[str] = []
    for act in acts:
        date = str(act.get("act_date") or "")[:10]
        start = str(act.get("play_at") or act.get("open_at") or "")[:5]
        end = str(act.get("end_at") or "")[:5]
        if not date:
            continue
        entry = date
        if start:
            entry += f" {start}"
            if end:
                entry += f"-{end}"
        if entry not in entries:
            entries.append(entry)
    return " / ".join(entries) or None


class TiffScraper(BaseScraper):
    """Scrapes Taiwan-related films from the Tokyo International Film Festival Films API.

    The API endpoint (api-{year}.tiff-jp.net) is only available after the TIFF
    lineup announcement (~September each year). ConnectionError/DNS failures are
    expected and handled gracefully for the months before announcement.
    """

    source_name = "tiff"

    def __init__(self, years: list[int] | None = None) -> None:
        self._years = years

    def _fetch_api(self, url: str, year: int, label: str) -> list[dict[str, Any]] | None:
        try:
            resp = requests.get(url, timeout=15)
            resp.raise_for_status()
        except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as exc:
            logger.info(
                "tiff: %s API not available for year %d (%s); skipping year",
                label,
                year,
                exc,
            )
            return None
        except requests.exceptions.HTTPError as exc:
            logger.warning("tiff: HTTP error from %s API (%s); skipping year", label, exc)
            return None
        except Exception as exc:
            logger.warning("tiff: unexpected error fetching %s API: %s", label, exc)
            return None

        try:
            payload = resp.json()
        except Exception as exc:
            logger.warning("tiff: failed to parse %s API JSON: %s", label, exc)
            return None
        if not isinstance(payload, list):
            logger.warning("tiff: %s API returned a non-list payload; skipping year", label)
            return None
        return [item for item in payload if isinstance(item, dict)]

    def scrape(self) -> list[Event]:
        events: list[Event] = []
        years = self._years or [datetime.now(timezone.utc).year]
        for year in years:
            films = self._fetch_api(_API_URL.format(year=year), year, "films")
            if films is None:
                continue
            venues = self._fetch_api(_VENUES_API_URL.format(year=year), year, "venues")
            if venues is None:
                continue
            screen_map = _screen_to_nearest_cinema(venues)
            for film in films:
                made_in = film.get("made_in_en") or ""
                if "Taiwan" not in made_in:
                    continue
                resolved_venues = _resolve_film_venues(film, screen_map)
                if resolved_venues is None:
                    continue
                event = self._build_event(film, year, resolved_venues)
                if event:
                    events.append(event)

        logger.info("tiff: %d Taiwan films found (years=%s)", len(events), years)
        return events

    def _build_event(
        self,
        film: dict[str, Any],
        year: int,
        venues: list[dict[str, Any]],
    ) -> Optional[Event]:
        film_id = film.get("film_identifier", "")
        if not film_id:
            return None

        source_id = f"tiff_{film_id}"
        source_url = _FILM_PAGE_URL.format(year=year, film_id=film_id)

        title_ja = film.get("title_ja") or ""
        title_en = film.get("title_en") or ""
        original_title = film.get("original_title") or ""

        name_ja = film.get("title_ja") or original_title or title_en or None
        raw_title = film.get("title_ja") or title_en or film_id

        # Lookup Chinese/English titles via eiga.com
        name_zh: Optional[str] = None
        name_en_lookup: Optional[str] = None
        if name_ja:
            try:
                name_zh, name_en_lookup, _ = lookup_movie_titles(name_ja)
            except Exception:
                pass

        name_en_final: Optional[str] = title_en or name_en_lookup or name_ja or None

        # acts / screening dates
        acts = film.get("acts") or []
        act_dates = sorted(set(a["act_date"][:10] for a in acts if a.get("act_date")))
        if not act_dates:
            return None

        y, m, d = [int(x) for x in act_dates[0].split("-")]
        start_date = datetime(y, m, d, tzinfo=timezone.utc)

        end_date: Optional[datetime] = None
        if len(act_dates) > 1:
            y2, m2, d2 = [int(x) for x in act_dates[-1].split("-")]
            end_date = datetime(y2, m2, d2, tzinfo=timezone.utc)

        # price_info — strip HTML tags
        price_info: Optional[str] = None
        if acts:
            raw_price = acts[0].get("ticket_price_en") or acts[0].get("ticket_price_ja")
            if raw_price:
                price_info = _HTML_TAG_RE.sub(" ", raw_price).strip()

        # raw_description
        parts = []
        if film.get("exp_ja"):
            parts.append(film["exp_ja"])
        if film.get("exp_en"):
            parts.append(f"[EN] {film['exp_en']}")
        if film.get("director_ja"):
            parts.append(f"監督：{film['director_ja']}")
        if film.get("made_in_en"):
            parts.append(f"制作国：{film['made_in_en']}")
        screening_dates = sorted(set(a["act_date"][:10] for a in acts if a.get("act_date")))
        parts.append(f"上映日：{', '.join(screening_dates)}")
        raw_description = "\n\n".join(parts).replace("\x00", "")[:4000]

        location_name = "・".join(venue["canonical_name_ja"] for venue in venues) or None
        prefectures: list[str] = []
        for venue in venues:
            venue_prefectures = venue.get("prefectures") or [venue.get("prefecture")]
            for prefecture in venue_prefectures:
                if prefecture and prefecture not in prefectures:
                    prefectures.append(prefecture)

        return Event(
            source_name=self.source_name,
            source_id=source_id,
            source_url=source_url,
            original_language="ja",
            raw_title=raw_title,
            raw_description=raw_description,
            name_ja=name_ja,
            name_en=name_en_final,
            name_zh=name_zh,
            start_date=start_date,
            end_date=end_date,
            location_name=location_name,
            location_address=None,
            location_prefectures=prefectures,
            venue_ids=[str(venue["id"]) for venue in venues],
            business_hours=_screening_hours(acts),
            category=["movie"],
            event_form=["screening"],
            director=film.get("director_ja"),
            price_info=price_info,
            official_url=film.get("url"),
        )
