"""One-off: fix Taiwan Cultural Center location pollution (PR-1).

What this script does:
1) Restores known false-positive multi-city parent event if it was overwritten.
2) Fixes true C-class TCC address pollution and locks corrected fields.
3) Backfills B-class multi-city parent `location_prefectures` from raw text.

Usage:
  python _oneoff_fix_tcc_locations.py --dry-run
  python _oneoff_fix_tcc_locations.py
"""

from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass

from dotenv import load_dotenv

from database import _get_client


SOURCE_NAME = "taiwan_cultural_center"
KNOWN_MULTI_CITY_FALSE_POSITIVE_ID = "51f7cd44-1a45-4f01-af24-0d6750536f41"

TCC_AUTHORITATIVE = {
    "location_name": "台北駐日経済文化代表処 台湾文化センター",
    "location_address": "東京都港区虎ノ門1-1-12 虎ノ門ビル2階",
    "location_prefectures": ["東京都"],
    "location_name_zh": "台北駐日經濟文化代表處 台灣文化中心",
    "location_name_en": "Taiwan Cultural Center, Taipei Economic and Cultural Representative Office in Japan",
}

LOCATION_LOCK_FIELDS = (
    "location_name",
    "location_address",
    "location_prefectures",
    "location_name_zh",
    "location_name_en",
)

TOKEN_TO_PREF = {
    "北海道": "北海道",
    "東京": "東京都",
    "東京都": "東京都",
    "大阪": "大阪府",
    "大阪府": "大阪府",
    "京都": "京都府",
    "京都府": "京都府",
    "神奈川": "神奈川県",
    "神奈川県": "神奈川県",
    "福岡": "福岡県",
    "福岡県": "福岡県",
    "愛知": "愛知県",
    "愛知県": "愛知県",
    "宮城": "宮城県",
    "宮城県": "宮城県",
    "兵庫": "兵庫県",
    "兵庫県": "兵庫県",
    "沖縄": "沖縄県",
    "沖縄県": "沖縄県",
    "仙台": "宮城県",
    "横浜": "神奈川県",
    "神戸": "兵庫県",
    "札幌": "北海道",
    "名古屋": "愛知県",
}

PREF_ORDER = [
    "北海道",
    "東京都",
    "神奈川県",
    "大阪府",
    "京都府",
    "福岡県",
    "愛知県",
    "宮城県",
    "兵庫県",
    "沖縄県",
]


@dataclass
class Result:
    c_candidates: int = 0
    c_skipped_multi_city: int = 0
    c_fixed: int = 0
    b_candidates: int = 0
    b_fixed: int = 0
    restored_false_positive: int = 0


def _pref_sort_key(pref: str) -> tuple[int, str]:
    try:
        return (PREF_ORDER.index(pref), pref)
    except ValueError:
        return (999, pref)


def _normalize_pref_list(values: list[str] | None) -> list[str]:
    if not values:
        return []
    out: set[str] = set()
    for value in values:
        s = (value or "").strip()
        if not s:
            continue
        out.add(TOKEN_TO_PREF.get(s, s))
    return sorted(out, key=_pref_sort_key)


def _detect_distinct_prefectures(raw_text: str | None, max_chars: int = 2000) -> list[str]:
    text = (raw_text or "")[:max_chars]
    found: set[str] = set()
    for token, pref in TOKEN_TO_PREF.items():
        if token in text:
            found.add(pref)
    return sorted(found, key=_pref_sort_key)


def _is_multi_city(raw_text: str | None) -> bool:
    return len(_detect_distinct_prefectures(raw_text)) >= 2


def _corrected_value(val: object) -> str:
    if isinstance(val, list):
        return json.dumps(val, ensure_ascii=False)
    return "" if val is None else str(val)


def _upsert_locks(sb, event_id: str, values: dict[str, object], fields: tuple[str, ...]) -> None:
    rows = [
        {
            "event_id": event_id,
            "field_name": field,
            "corrected_value": _corrected_value(values.get(field)),
            "corrected_by": None,
        }
        for field in fields
    ]
    sb.table("field_corrections").upsert(rows, on_conflict="event_id,field_name").execute()


def _fetch_tcc_events(sb) -> list[dict]:
    return (
        sb.table("events")
        .select(
            "id,name_ja,raw_description,location_name,location_address,"
            "location_prefectures,parent_event_id"
        )
        .eq("source_name", SOURCE_NAME)
        .eq("is_active", True)
        .execute()
        .data
        or []
    )


def _restore_known_false_positive(sb, dry_run: bool) -> int:
    row = (
        sb.table("events")
        .select("id,raw_description")
        .eq("id", KNOWN_MULTI_CITY_FALSE_POSITIVE_ID)
        .limit(1)
        .execute()
        .data
    )
    if not row:
        return 0

    detected = _detect_distinct_prefectures(row[0].get("raw_description"))
    if len(detected) < 2:
        return 0

    restored = {
        "location_name": "台湾文化センター・北海道・神奈川・京都・大阪",
        "location_address": None,
        "location_prefectures": ["東京都", "北海道", "神奈川県", "京都府", "大阪府"],
    }

    if dry_run:
        print(
            f"[DRY-RUN] restore false-positive {KNOWN_MULTI_CITY_FALSE_POSITIVE_ID[:8]}: "
            f"prefectures={restored['location_prefectures']}"
        )
        return 1

    sb.table("events").update(restored).eq("id", KNOWN_MULTI_CITY_FALSE_POSITIVE_ID).execute()

    # Remove wrong locks generated by the first run, then re-lock only stable fields.
    sb.table("field_corrections").delete().eq("event_id", KNOWN_MULTI_CITY_FALSE_POSITIVE_ID).in_(
        "field_name", list(LOCATION_LOCK_FIELDS)
    ).execute()
    _upsert_locks(
        sb,
        KNOWN_MULTI_CITY_FALSE_POSITIVE_ID,
        {
            "location_address": None,
            "location_prefectures": restored["location_prefectures"],
        },
        ("location_address", "location_prefectures"),
    )
    print(f"[APPLY] restored false-positive {KNOWN_MULTI_CITY_FALSE_POSITIVE_ID[:8]}")
    return 1


def run(dry_run: bool) -> Result:
    sb = _get_client()
    result = Result()

    result.restored_false_positive = _restore_known_false_positive(sb, dry_run)

    events = _fetch_tcc_events(sb)
    c_targets: list[dict] = []

    for event in events:
        loc_name = event.get("location_name") or ""
        loc_addr = event.get("location_address") or ""

        if "台湾文化" in loc_name and "虎ノ門" not in loc_addr:
            result.c_candidates += 1
            if _is_multi_city(event.get("raw_description")):
                result.c_skipped_multi_city += 1
                print(f"[SKIP-C] {event['id'][:8]} multi-city signal in raw_description")
            else:
                c_targets.append(event)

    for event in c_targets:
        eid = event["id"]
        if dry_run:
            print(f"[DRY-RUN C] {eid[:8]} -> canonical TCC address")
            result.c_fixed += 1
            continue

        sb.table("events").update(TCC_AUTHORITATIVE).eq("id", eid).execute()
        _upsert_locks(sb, eid, TCC_AUTHORITATIVE, LOCATION_LOCK_FIELDS)
        print(f"[APPLY C] {eid[:8]} fixed + FC locks")
        result.c_fixed += 1

    # B-class: parent events with multi-city signals in raw text.
    for event in events:
        if event.get("parent_event_id") is not None:
            continue
        detected = _detect_distinct_prefectures(event.get("raw_description"))
        if len(detected) < 2:
            continue

        result.b_candidates += 1
        existing = _normalize_pref_list(event.get("location_prefectures"))
        merged = sorted(set(existing) | set(detected), key=_pref_sort_key)
        if merged == existing:
            continue

        if dry_run:
            print(f"[DRY-RUN B] {event['id'][:8]} {existing} -> {merged}")
            result.b_fixed += 1
            continue

        sb.table("events").update({"location_prefectures": merged}).eq("id", event["id"]).execute()
        print(f"[APPLY B] {event['id'][:8]} location_prefectures={merged}")
        result.b_fixed += 1

    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Fix TCC location pollution and multi-city prefectures")
    parser.add_argument("--dry-run", action="store_true", help="Show updates without writing DB")
    args = parser.parse_args()

    load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))

    res = run(args.dry_run)
    mode = "DRY-RUN" if args.dry_run else "APPLY"
    print(
        f"[{mode}] done | restored_false_positive={res.restored_false_positive} "
        f"C: candidates={res.c_candidates} skipped_multi={res.c_skipped_multi_city} fixed={res.c_fixed} "
        f"B: candidates={res.b_candidates} fixed={res.b_fixed}"
    )


if __name__ == "__main__":
    main()
