#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


MARKER = "<!-- generated by scripts/sync_ai_adapters.py — do not edit -->"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def kebab(value: str) -> str:
    text = value.replace("_", "-").lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")


def one_line(value: object) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def yaml_quote(value: object) -> str:
    text = str(value or "")
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    text = text.replace("\n", "\\n")
    return f'"{text}"'


def split_inline_list(value: str) -> list[str]:
    inner = value.strip()[1:-1].strip()
    if not inner:
        return []
    parts: list[str] = []
    current: list[str] = []
    quote = ""
    escape = False
    for char in inner:
        if escape:
            current.append(char)
            escape = False
            continue
        if char == "\\" and quote == '"':
            current.append(char)
            escape = True
            continue
        if quote:
            current.append(char)
            if char == quote:
                quote = ""
            continue
        if char in ("'", '"'):
            quote = char
            current.append(char)
            continue
        if char == ",":
            parts.append("".join(current).strip())
            current = []
            continue
        current.append(char)
    parts.append("".join(current).strip())
    return [str(parse_scalar(part)) for part in parts if part]


def parse_scalar(value: str) -> object:
    text = value.strip()
    if not text:
        return ""
    if text.startswith("[") and text.endswith("]"):
        return split_inline_list(text)
    if (text.startswith('"') and text.endswith('"')) or (
        text.startswith("'") and text.endswith("'")
    ):
        try:
            parsed = ast.literal_eval(text)
            return parsed if isinstance(parsed, str) else text[1:-1]
        except (SyntaxError, ValueError):
            return text[1:-1]
    if text in {"true", "false"}:
        return text == "true"
    return text


def split_key_value(text: str) -> tuple[str, str] | None:
    if ":" not in text:
        return None
    key, value = text.split(":", 1)
    key = key.strip()
    if not key:
        return None
    return key, value.strip()


def parse_list_block(block: list[str]) -> list[object]:
    items: list[object] = []
    current: dict[str, object] | None = None
    for raw in block:
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("- "):
            item = stripped[2:].strip()
            pair = split_key_value(item)
            if pair:
                current = {pair[0]: parse_scalar(pair[1])}
                items.append(current)
            else:
                current = None
                items.append(parse_scalar(item))
            continue
        if current is not None:
            pair = split_key_value(stripped)
            if pair:
                current[pair[0]] = parse_scalar(pair[1])
    return items


def parse_frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    lines = text[4:end].splitlines()
    data: dict[str, object] = {}
    index = 0
    while index < len(lines):
        raw = lines[index]
        if not raw.strip() or raw.startswith((" ", "\t")):
            index += 1
            continue
        pair = split_key_value(raw)
        if not pair:
            index += 1
            continue
        key, value = pair
        if value:
            data[key] = parse_scalar(value)
            index += 1
            continue
        block: list[str] = []
        index += 1
        while index < len(lines) and (
            not lines[index].strip() or lines[index].startswith((" ", "\t"))
        ):
            block.append(lines[index])
            index += 1
        if any(line.strip().startswith("- ") for line in block):
            data[key] = parse_list_block(block)
        else:
            data[key] = "\n".join(line.strip() for line in block if line.strip())
    return data


def agent_sources(root: Path) -> list[Path]:
    base = root / ".github" / "agents"
    return sorted(base.glob("*.agent.md")) + sorted((base / "subagents").glob("*.agent.md"))


def skill_sources(root: Path) -> list[Path]:
    return sorted((root / ".github" / "skills").glob("**/SKILL.md"))


def prompt_sources(root: Path) -> list[Path]:
    return sorted((root / ".github" / "prompts").glob("*.prompt.md"))


def resolved_skill_names(root: Path) -> dict[Path, str]:
    skills_root = root / ".github" / "skills"
    bases: dict[Path, str] = {}
    grouped: dict[str, list[Path]] = {}
    for path in skill_sources(root):
        meta = parse_frontmatter(path)
        base_name = kebab(str(meta.get("name") or path.parent.name))
        bases[path] = base_name
        grouped.setdefault(base_name, []).append(path)

    resolved: dict[Path, str] = {}
    for base_name, paths in grouped.items():
        if len(paths) == 1:
            resolved[paths[0]] = base_name
            continue
        for path in paths:
            parent = path.parent.parent
            if parent == skills_root:
                resolved[path] = base_name
            else:
                resolved[path] = kebab(f"{parent.name}-{base_name}")

    names = list(resolved.values())
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise SystemExit(
            "skill name conflicts after prefixing: " + ", ".join(duplicates)
        )
    return resolved


def agent_outputs(root: Path) -> dict[Path, str]:
    sources = agent_sources(root)
    metas = {path: parse_frontmatter(path) for path in sources}
    name_map = {
        one_line(meta.get("name") or path.stem.removesuffix(".agent")): kebab(
            one_line(meta.get("name") or path.stem.removesuffix(".agent"))
        )
        for path, meta in metas.items()
    }
    outputs: dict[Path, str] = {}
    for path in sources:
        meta = metas[path]
        original_name = one_line(meta.get("name") or path.stem.removesuffix(".agent"))
        out_name = name_map[original_name]
        description = one_line(meta.get("description") or original_name)
        source = rel(path, root)
        lines = [
            "---",
            f"name: {out_name}",
            f"description: {yaml_quote(description)}",
            "---",
            "",
            MARKER,
            "",
            f"你是 {original_name} agent。開始前完整讀取並遵循 `{source}`；其中 Copilot 專屬工具與機制依 repo root `AGENTS.md` 的『Copilot 對照表』轉換；忽略該檔 frontmatter 的 model/handoffs。",
        ]
        handoffs = meta.get("handoffs")
        if isinstance(handoffs, list) and handoffs:
            lines += ["", "完成後建議的下一步："]
            for item in handoffs:
                if not isinstance(item, dict):
                    continue
                label = one_line(item.get("label"))
                target = one_line(item.get("agent"))
                if not label or not target:
                    continue
                target_name = name_map.get(target, kebab(target))
                prompt = one_line(item.get("prompt"))
                suffix = f"（建議提示：{prompt}）" if prompt else ""
                lines.append(f"- {label}：切換到 {target_name}{suffix}")
        lines.append("")
        outputs[Path(".claude") / "agents" / f"{out_name}.md"] = "\n".join(lines)
    return outputs


def skill_outputs(root: Path) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for path, out_name in resolved_skill_names(root).items():
        meta = parse_frontmatter(path)
        description = one_line(meta.get("description") or out_name)
        source = rel(path, root)
        content = "\n".join(
            [
                "---",
                f"name: {out_name}",
                f"description: {yaml_quote(description)}",
                "---",
                "",
                MARKER,
                "",
                f"完整讀取並遵循 `{source}`；同資料夾其他檔案（history.md、scripts 等）以該路徑為準。",
                "",
            ]
        )
        for base in (Path(".claude") / "skills", Path(".agents") / "skills"):
            outputs[base / out_name / "SKILL.md"] = content
    return outputs


def prompt_outputs(root: Path) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for path in prompt_sources(root):
        meta = parse_frontmatter(path)
        name = path.name.removesuffix(".prompt.md")
        description = one_line(meta.get("description") or name)
        source = rel(path, root)
        content = "\n".join(
            [
                "---",
                f"description: {yaml_quote(description)}",
                "---",
                "",
                MARKER,
                "",
                f"完整讀取並執行 `{source}`；使用者附加參數：$ARGUMENTS",
                "",
            ]
        )
        outputs[Path(".claude") / "commands" / f"{name}.md"] = content
    return outputs


def expected_outputs(root: Path) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for part in (agent_outputs(root), skill_outputs(root), prompt_outputs(root)):
        overlap = set(outputs) & set(part)
        if overlap:
            raise SystemExit(
                "duplicate output paths: "
                + ", ".join(sorted(path.as_posix() for path in overlap))
            )
        outputs.update(part)
    return outputs


def generated_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for base in (
        root / ".claude" / "agents",
        root / ".claude" / "commands",
        root / ".claude" / "skills",
        root / ".agents" / "skills",
    ):
        if not base.exists():
            continue
        for path in base.rglob("*.md"):
            try:
                if MARKER in path.read_text(encoding="utf-8"):
                    files.append(path)
            except UnicodeDecodeError:
                continue
    return files


def check(root: Path, expected: dict[Path, str]) -> int:
    generated = {path.relative_to(root) for path in generated_files(root)}
    expected_paths = set(expected)
    changed: list[str] = []
    for path in sorted(expected_paths):
        full = root / path
        if not full.exists():
            changed.append(f"missing {path.as_posix()}")
            continue
        actual = full.read_text(encoding="utf-8")
        if actual != expected[path]:
            changed.append(f"changed {path.as_posix()}")
    for path in sorted(generated - expected_paths):
        changed.append(f"stale {path.as_posix()}")
    for line in changed:
        print(line)
    return 1 if changed else 0


def write_outputs(root: Path, expected: dict[Path, str]) -> None:
    for path in generated_files(root):
        path.unlink()
    for path, content in sorted(expected.items()):
        full = root / path
        if full.exists() and MARKER not in full.read_text(encoding="utf-8"):
            raise SystemExit(f"refusing to overwrite non-generated file: {path}")
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = repo_root()
    expected = expected_outputs(root)
    if args.check:
        return check(root, expected)
    write_outputs(root, expected)
    print(f"generated {len(expected)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
